-- MySQL Script generated by MySQL Workbench
-- Mon Jan  3 03:17:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 18070001022_SE2222_Project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 18070001022_SE2222_Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `18070001022_SE2222_Project` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema week10_part1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema week07_join
-- -----------------------------------------------------
USE `18070001022_SE2222_Project` ;

-- -----------------------------------------------------
-- Table `18070001022_SE2222_Project`.`Publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `18070001022_SE2222_Project`.`Publisher` ;

CREATE TABLE IF NOT EXISTS `18070001022_SE2222_Project`.`Publisher` (
  `PublisherID` INT AUTO_INCREMENT,
  `Publisher_Name` VARCHAR(50) NOT NULL,
  `Publisher_Adress` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PublisherID`))
ENGINE = InnoDB;

INSERT INTO Publisher (Publisher_Name, Publisher_Adress) VALUES ("Penquin", "152 street no 25");
INSERT INTO Publisher (Publisher_Name, Publisher_Adress) VALUES ("Bloomsbury Publishing", "355 street no 1");
INSERT INTO Publisher (Publisher_Name, Publisher_Adress) VALUES ("Gnome Press", "123 street no 9");
INSERT INTO Publisher (Publisher_Name, Publisher_Adress) VALUES ("Can Yayınları", "151 street no 63");
INSERT INTO Publisher (Publisher_Name, Publisher_Adress) VALUES ("Kuzey Yayınları", "173 street no 89");
-- -----------------------------------------------------
-- Table `18070001022_SE2222_Project`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `18070001022_SE2222_Project`.`Author` ;

CREATE TABLE IF NOT EXISTS `18070001022_SE2222_Project`.`Author` (
  `AuthorID` INT AUTO_INCREMENT,
  `Author_NameAndSurname` VARCHAR(50) NOT NULL,
  `Author_WrittenBook` VARCHAR(45) NOT NULL,
  `Author_Gender` VARCHAR(1) NOT NULL,
  `Author_Birthday` DATE NULL,
  `Author_Country` VARCHAR(45) NULL,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB;

INSERT INTO Author (Author_NameAndSurname, Author_WrittenBook,Author_Gender,Author_Birthday,Author_Country) VALUES ("Dan Brown", "Left Leg","M","1960-08-12","England");
INSERT INTO Author (Author_NameAndSurname, Author_WrittenBook,Author_Gender,Author_Birthday,Author_Country) VALUES ("Isaac Asimov", "Foundation","M","1923-04-27","Russia");
INSERT INTO Author (Author_NameAndSurname, Author_WrittenBook,Author_Gender,Author_Birthday,Author_Country) VALUES ("J. K. Rowling", "Harry Potter","F","1978-02-15","England");
INSERT INTO Author (Author_NameAndSurname, Author_WrittenBook,Author_Gender,Author_Birthday,Author_Country) VALUES ("Stefan Zweig", "The Royal Game","M","1964-05-14","Russia");
INSERT INTO Author (Author_NameAndSurname, Author_WrittenBook,Author_Gender,Author_Birthday,Author_Country) VALUES ("Oğuz Atay", "Tehlikeli Oyunlar","M","1956-07-23","Turkey");

-- -----------------------------------------------------
-- Table `18070001022_SE2222_Project`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `18070001022_SE2222_Project`.`Book` ;

CREATE TABLE IF NOT EXISTS `18070001022_SE2222_Project`.`Book` (
  `Book_ISBN` INT NOT NULL,
  `Book_Title` VARCHAR(45) NOT NULL,
  `Book_Category` VARCHAR(45) NOT NULL,
  `NumberOfPages` INT NOT NULL,
  `Author_Of_Book` VARCHAR(50) NOT NULL,
  `Publisher_Of_Book` VARCHAR(50) NOT NULL,
  `Publisher_ID` INT NOT NULL,
  `Author_ID` INT NOT NULL,
  PRIMARY KEY (`Book_ISBN`),
  INDEX `Publisher_idx` (`Publisher_ID` ASC) VISIBLE,
  INDEX `Author_idx` (`Author_ID` ASC) VISIBLE,
  CONSTRAINT `Publisher`
    FOREIGN KEY (`Publisher_ID`)
    REFERENCES `18070001022_SE2222_Project`.`Publisher` (`PublisherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Author`
    FOREIGN KEY (`Author_ID`)
    REFERENCES `18070001022_SE2222_Project`.`Author` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Book (Book_ISBN, Book_Title ,Book_Category,NumberOfPages,Author_Of_Book,Publisher_Of_Book,Publisher_ID,Author_ID) VALUES (23423, "Left Leg","Drama",156,"Dan Brown","Penguin",1,1);
INSERT INTO Book (Book_ISBN, Book_Title ,Book_Category,NumberOfPages,Author_Of_Book,Publisher_Of_Book,Publisher_ID,Author_ID) VALUES (12341, "Foundation","Advanture",253,"Isaac Asimov","Gnome Press",3,2);
INSERT INTO Book (Book_ISBN, Book_Title ,Book_Category,NumberOfPages,Author_Of_Book,Publisher_Of_Book,Publisher_ID,Author_ID) VALUES (43734, "The Royal Game","Drama",132,"Stefan Zweig","Penguin",5,4);
INSERT INTO Book (Book_ISBN, Book_Title ,Book_Category,NumberOfPages,Author_Of_Book,Publisher_Of_Book,Publisher_ID,Author_ID) VALUES (15623, "Harry Potter","Advanture",234,"J. K. Rowling","Bloomsbury Publishing",2,3);
INSERT INTO Book (Book_ISBN, Book_Title ,Book_Category,NumberOfPages,Author_Of_Book,Publisher_Of_Book,Publisher_ID,Author_ID) VALUES (35462, "Tehlikeli Oyunlar","Drama",368,"Oğuz Atay","Penguin",4,5);

-- -----------------------------------------------------
-- Table `18070001022_SE2222_Project`.`People`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `18070001022_SE2222_Project`.`People` ;

CREATE TABLE IF NOT EXISTS `18070001022_SE2222_Project`.`People` (
  `PeopleID` INT AUTO_INCREMENT,
  `Person_NameAndSurname` VARCHAR(50) NOT NULL,
  `NameOfReadBook` VARCHAR(45) NOT NULL,
  `Person_Birthday` DATE NOT NULL,
  `YearOfRead` INT NOT NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;

INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Damla Ciğeroğlu", "Foundation","2004-05-31","2021");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Engincan Ciğeroğlu", "Foundation","2000-07-08","2019");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Duygu Aydın", "Harry Potter","1995-03-12","2010");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Burak Yakan", "Tehlikeli Oyunlar","1985-06-01","2000");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Helin Arıcı", "The Royal Game","1975-12-04","1995");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Sarp Nurlu", "Left Leg","1992-05-30","2010");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Ecemnaz Balkan", "Foundation","2000-04-26","2020");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Duygu Nurlu", "Harry Potter","1998-02-14","2015");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Yasemin Büyükgümüş", "Harry Potter","2001-07-08","2014");
INSERT INTO People (Person_NameAndSurname, NameOfReadBook, Person_Birthday, YearOfRead) VALUES ("Ufuk Arıcı", "Harry Potter","2002-03-23","2014");


-- -----------------------------------------------------
-- Table `18070001022_SE2222_Project`.`Book_has_People`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `18070001022_SE2222_Project`.`Book_has_People` ;

CREATE TABLE IF NOT EXISTS `18070001022_SE2222_Project`.`Book_has_People` (
  `Book_ISBN` INT NOT NULL,
  `People_PeopleID` INT NOT NULL,
  PRIMARY KEY (`Book_ISBN`, `People_PeopleID`),
  INDEX `fk_Book_has_People_People1_idx` (`People_PeopleID` ASC) VISIBLE,
  INDEX `fk_Book_has_People_Book1_idx` (`Book_ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Book_has_People_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `18070001022_SE2222_Project`.`Book` (`Book_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_People_People1`
    FOREIGN KEY (`People_PeopleID`)
    REFERENCES `18070001022_SE2222_Project`.`People` (`PeopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `18070001022_SE2222_Project`.`People_has_Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `18070001022_SE2222_Project`.`People_has_Book` ;

CREATE TABLE IF NOT EXISTS `18070001022_SE2222_Project`.`People_has_Book` (
  `People_PeopleID` INT NOT NULL,
  `Book_ISBN` INT NOT NULL,
  PRIMARY KEY (`People_PeopleID`, `Book_ISBN`),
  INDEX `fk_People_has_Book_Book1_idx` (`Book_ISBN` ASC) VISIBLE,
  INDEX `fk_People_has_Book_People1_idx` (`People_PeopleID` ASC) VISIBLE,
  CONSTRAINT `fk_People_has_Book_People1`
    FOREIGN KEY (`People_PeopleID`)
    REFERENCES `18070001022_SE2222_Project`.`People` (`PeopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_People_has_Book_Book1`
    FOREIGN KEY (`Book_ISBN`)
    REFERENCES `18070001022_SE2222_Project`.`Book` (`Book_ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
